# Unit Normalization Configuration
#
# Defines canonical units and conversion rules for metals/materials.

# Ferro-Alloys
FeCr:
  canonical_unit: "USD/lb"
  canonical_basis: "Cr contained"
  requires:
    - "Cr_pct"
    - "ton_system"
  conversion_note: "Convert $/t alloy to $/lb Cr contained"
  source: "Fastmarkets FeCr specifications"

APT:
  canonical_unit: "USD/mtu WO3"
  canonical_basis: "WO3 basis"
  requires:
    - "WO3_pct"
  conversion_note: "Convert $/t APT to $/mtu WO3"
  source: "Fastmarkets APT specifications"

# Base Metals
Copper:
  canonical_unit: "USD/lb"
  canonical_basis: "Cu contained"
  requires: []
  conversion_note: "Pure metal, simple mass conversion"

Aluminum:
  canonical_unit: "USD/lb"
  canonical_basis: "Al contained"
  requires: []

Nickel:
  canonical_unit: "USD/lb"
  canonical_basis: "Ni contained"
  requires: []

# Precious Metals
Gold:
  canonical_unit: "USD/oz"
  canonical_basis: "Au contained"
  requires: []

Silver:
  canonical_unit: "USD/oz"
  canonical_basis: "Ag contained"
  requires: []

Platinum:
  canonical_unit: "USD/oz"
  canonical_basis: "Pt contained"
  requires: []

# Conversion Constants
conversion_constants:
  metric_ton_to_lbs: 2204.62
  short_ton_to_lbs: 2000.0
  long_ton_to_lbs: 2240.0
  kg_to_lbs: 2.20462
  troy_oz_per_kg: 32.1507
  grams_per_troy_oz: 31.1035
  mtu_per_metric_ton: 10.0
